apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection-service
  name: udaconnect-connection-service
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    nodePort: 30002
  selector:
    service: udaconnect-connection-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection-service
  name: udaconnect-connection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection-service
  template:
    metadata:
      labels:
        service: udaconnect-connection-service
    spec:
      containers:
      - image: ilem0n/udaconnect-connections-service:latest
        name: udaconnect-connection-service
        # currently the data is hard coded and will be injected at runtime.
        # When using a real kafka, it would be configured here like:
        # env:
        #   name: "KAFKA_BOOTSTRAP_SERVERS"
        #   value: "kafka:9092"
        imagePullPolicy: Always
      restartPolicy: Always
