# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connections.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model_pb2 as model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63onnections.proto\x12\x0b\x63onnections\x1a\x0bmodel.proto\"&\n\x12\x43onnectionsRequest\x12\x10\n\x08personId\x18\x01 \x01(\x05\"I\n\x10\x43onnectionsReply\x12\x10\n\x08personId\x18\x01 \x01(\x05\x12#\n\x0b\x63onnections\x18\x02 \x03(\x0b\x32\x0e.ConnectionDTO2a\n\x0b\x43onnections\x12R\n\x0eGetConnections\x12\x1f.connections.ConnectionsRequest\x1a\x1d.connections.ConnectionsReply\"\x00\x42\x30\n\x18\x64\x65.ilem0n.udaconnect.rpcB\x12\x43onnectionsServiceP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connections_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030de.ilem0n.udaconnect.rpcB\022ConnectionsServiceP\001'
  _CONNECTIONSREQUEST._serialized_start=47
  _CONNECTIONSREQUEST._serialized_end=85
  _CONNECTIONSREPLY._serialized_start=87
  _CONNECTIONSREPLY._serialized_end=160
  _CONNECTIONS._serialized_start=162
  _CONNECTIONS._serialized_end=259
# @@protoc_insertion_point(module_scope)
