# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"E\n\x0bLocationDTO\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x11\n\tcreatedAt\x18\x03 \x01(\t\"Q\n\tPersonDTO\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfirstName\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\x13\n\x0b\x63ompanyName\x18\x04 \x01(\t\"K\n\rConnectionDTO\x12\x1e\n\x08location\x18\x01 \x01(\x0b\x32\x0c.LocationDTO\x12\x1a\n\x06person\x18\x02 \x01(\x0b\x32\n.PersonDTOB2\n\x1e\x64\x65.ilem0n.udaconnect.rpc.modelB\x0ePersonsServiceP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036de.ilem0n.udaconnect.rpc.modelB\016PersonsServiceP\001'
  _LOCATIONDTO._serialized_start=15
  _LOCATIONDTO._serialized_end=84
  _PERSONDTO._serialized_start=86
  _PERSONDTO._serialized_end=167
  _CONNECTIONDTO._serialized_start=169
  _CONNECTIONDTO._serialized_end=244
# @@protoc_insertion_point(module_scope)
