# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import persons_pb2 as persons__pb2


class PersonsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPersons = channel.unary_unary(
                '/persons.Persons/GetPersons',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=persons__pb2.PersonsReply.FromString,
                )


class PersonsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPersons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPersons': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersons,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=persons__pb2.PersonsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'persons.Persons', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Persons(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPersons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/persons.Persons/GetPersons',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            persons__pb2.PersonsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
